name: .NET Framework Desktop

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    env:
      Solution_Name: QUANLYHOCPHAN.sln
      DAL_Project_Path: DAL\DAL.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      # Add Dapper Package for DAL
      - name: Add Dapper package for BLL
        run: dotnet add ${{ env.DAL_Project_Path }} package Dapper

      # Execute all unit tests in the solution
      - name: Execute unit tests
        run: dotnet test
