name: .NET Framework Desktop

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Test:
    strategy:
      matrix:
        os: [windows-latest]
        dotnet: ['7.0.114', '7.0.14', '7.0.311']

    runs-on: ${{ matrix.os }}

    env:
      Solution_Name: QUANLYHOCPHAN.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore Packages
        run: nuget restore QUANLYHOCPHAN.sln

      - name: Execute unit tests
        run: dotnet test

      - name: Create new tool manifest
        run: dotnet new tool-manifest

      - name: Install dotnet stryker
        run: dotnet tool install dotnet-stryker

      - name: Execute mutation tests
        run: dotnet stryker
