name: .NET Framework Desktop

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Test:
    strategy:
      matrix:
        configuration: [windows-latest]

    runs-on: windows-latest

    env:
      Solution_Name: QUANLYHOCPHAN.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore Packages
        run: nuget restore QUANLYHOCPHAN.sln

      - name: Execute unit tests
        run: dotnet test

      - run: dotnet new tool-manifest

      - run: dotnet install dotnet-stryker

      - name: Execute mutation tests
        run: dotnet stryker
