name: .NET Framework Desktop

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    env:
      Solution_Name: QUANLYHOCPHAN.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install the .NET Core workload
      # - name: Install .NET Core
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: 7.0.x

      # - name: Install dependencies
      #   run: dotnet restore

      # - run: dotnet build QUANLYHOCPHAN.sln

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Restore Packages
        run: nuget restore QUANLYHOCPHAN.sln

      # Execute all unit tests in the solution
      - name: Execute unit tests
        run: dotnet test
